# Sesame5 UUID and 16-byte secret key.
sesame_id = "replace-me"
sesame_secret_key = "replace-me"

# Nature Remo LIGHT settings. These values are required.
nature_token = "replace-me"
nature_light_appliance_id = "replace-me"
nature_light_button = "on"
